services:
  db:
    container_name: "blog_db"
    image: postgres:16
    ports:
      - "5430:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db

  adminer:
    container_name: "blog_adminer"
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - db



