spring:
  application:
    name: blogify

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5430/db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
rsa:

  private-key: classpath:certs/private_key.pem
  public-key: classpath:certs/public_key.pem
  token-expire-in: 7d
